name: megabeast

channels:
    - astropy

dependencies:
    - astropy
    - Cython
    - matplotlib
    - numpy
    - sphinx-astropy
    - h5py
    - scipy
    - tqdm
#   - pip:
#       - dependency_from_pip
